### ISSUE TITLE
Runecraftory multiple bugs found

### ISSUE THREAD

**Issue by Emmiren** [Flemmli97/RuneCraftory#1]
** Bug Description: **
I cannot interact with any objects like the chests, blocks will not give anything when they are broken, monster gates won't spawn, and mobs won't move and cannot be hit by anything.

** How to reproduce: **
I'm not sure how you can reproduce the bug(s).

** What you think should have happened: **
Chests should be able to be opened, mobs should move and be able to get hit/ take damage, trees should drop wood, torches should be able to be picked up when broken, monster gates should spawn, and mobs shouldn't be static.

** Affected Versions. If you think the bug is caused by compability issues with other mods, include them here too: **

- RuneCraftory: RuneCraftory-a0.2.0[1.12.2].jar
- Minecraft: 1.12.2
- Forge: 1.12.2-forge 1.12.2-14.23.4.2725

** Log file. Don't copy paste it here. Use something like pastebin: **
https://pastebin.com/TvN9VGDp

**Comment by Flemmli97** [comment]
apparently solved, reopen if issue still persist
