### ISSUE TITLE
Missing some classes

### ISSUE THREAD

**Issue by Baytars** [Flemmli97/RuneCraftory#2]
> /path/to/my/mc/project/build/sources/main/java/com/flemmli97/runecraftory/common/init/ModBlocks.java:34: 错误: 找不到符号
import com.flemmli97.runecraftory.common.lib.enums.EnumMineralTier;
                                                  ^
  符号:   类 EnumMineralTier
  位置: 程序包 com.flemmli97.runecraftory.common.lib.enums
/path/to/my/mc/project/build/sources/main/java/com/flemmli97/runecraftory/common/utils/MineralBlockConverter.java:4: 错误: 找不到符号
import com.flemmli97.runecraftory.common.lib.enums.EnumMineralTier;
                                                  ^
  符号:   类 EnumMineralTier
  位置: 程序包 com.flemmli97.runecraftory.common.lib.enums
/path/to/my/mc/project/build/sources/main/java/com/flemmli97/runecraftory/common/utils/MineralBlockConverter.java:10: 错误: 找不到符号
	public static IBlockState getBrokenState(EnumMineralTier tier)
	                                         ^
  符号:   类 EnumMineralTier
  位置: 类 MineralBlockConverter
/path/to/my/mc/project/build/sources/main/java/com/flemmli97/runecraftory/common/utils/MineralBlockConverter.java:30: 错误: 找不到符号
	public static IBlockState getRestoredState(EnumMineralTier tier)
	                                           ^
  符号:   类 EnumMineralTier
  位置: 类 MineralBlockConverter
/path/to/my/mc/project/build/sources/main/java/com/flemmli97/runecraftory/common/world/MineralGenerator.java:8: 错误: 找不到符号
import com.flemmli97.runecraftory.common.lib.enums.EnumMineralTier;
                                                  ^
  符号:   类 EnumMineralTier
  位置: 程序包 com.flemmli97.runecraftory.common.lib.enums
/path/to/my/mc/project/build/sources/main/java/com/flemmli97/runecraftory/common/world/MineralGenerator.java:108: 错误: 找不到符号
	private void generateMineral(World world, BlockPos pos, EnumMineralTier tier)
	                                                        ^
  符号:   类 EnumMineralTier
  位置: 类 MineralGenerator
/path/to/my/mc/project/build/sources/main/java/com/flemmli97/runecraftory/common/world/MineralGenerator.java:119: 错误: 找不到符号
	private EnumMineralTier getRandomTier(World world, Random rand, BlockPos pos)
	        ^
  符号:   类 EnumMineralTier
  位置: 类 MineralGenerator
/path/to/my/mc/project/build/sources/main/java/com/flemmli97/runecraftory/common/world/MineralGenerator.java:160: 错误: 找不到符号
	private void generateNether(World world, BlockPos pos, EnumMineralTier tier)
	                                                       ^
  符号:   类 EnumMineralTier
  位置: 类 MineralGenerator
/path/to/my/mc/project/build/sources/main/java/com/flemmli97/runecraftory/common/potion/PotionSleep.java:4: 错误: 找不到符号
import com.flemmli97.runecraftory.common.lib.LibPotions;
                                            ^
  符号:   类 LibPotions
  位置: 程序包 com.flemmli97.runecraftory.common.lib
/path/to/my/mc/project/build/sources/main/java/com/flemmli97/runecraftory/common/potion/PotionParalysis.java:3: 错误: 找不到符号
import com.flemmli97.runecraftory.common.lib.LibPotions;
                                            ^
  符号:   类 LibPotions
  位置: 程序包 com.flemmli97.runecraftory.common.lib
/path/to/my/mc/project/build/sources/main/java/com/flemmli97/runecraftory/common/potion/PotionPoison.java:6: 错误: 找不到符号
import com.flemmli97.runecraftory.common.lib.LibPotions;
                                            ^
  符号:   类 LibPotions
  位置: 程序包 com.flemmli97.runecraftory.common.lib
/path/to/my/mc/project/build/sources/main/java/com/flemmli97/runecraftory/common/potion/PotionFatigue.java:3: 错误: 找不到符号
import com.flemmli97.runecraftory.common.lib.LibPotions;
                                            ^
  符号:   类 LibPotions
  位置: 程序包 com.flemmli97.runecraftory.common.lib
/path/to/my/mc/project/build/sources/main/java/com/flemmli97/runecraftory/common/potion/PotionCold.java:5: 错误: 找不到符号
import com.flemmli97.runecraftory.common.lib.LibPotions;
                                            ^
  符号:   类 LibPotions
  位置: 程序包 com.flemmli97.runecraftory.common.lib
/path/to/my/mc/project/build/sources/main/java/com/flemmli97/runecraftory/common/potion/PotionSeal.java:3: 错误: 找不到符号
import com.flemmli97.runecraftory.common.lib.LibPotions;
                                            ^
  符号:   类 LibPotions
  位置: 程序包 com.flemmli97.runecraftory.common.lib
/path/to/my/mc/project/build/sources/main/java/com/flemmli97/runecraftory/common/blocks/BlockBrokenMineral.java:10: 错误: 找不到符号
import com.flemmli97.runecraftory.common.lib.enums.EnumMineralTier;
                                                  ^
  符号:   类 EnumMineralTier
  位置: 程序包 com.flemmli97.runecraftory.common.lib.enums
/path/to/my/mc/project/build/sources/main/java/com/flemmli97/runecraftory/common/blocks/BlockBrokenMineral.java:35: 错误: 找不到符号
	private final EnumMineralTier tier;
	              ^
  符号:   类 EnumMineralTier
  位置: 类 BlockBrokenMineral
/path/to/my/mc/project/build/sources/main/java/com/flemmli97/runecraftory/common/blocks/BlockBrokenMineral.java:36: 错误: 找不到符号
	public BlockBrokenMineral(EnumMineralTier tier) {
	                          ^
  符号:   类 EnumMineralTier
  位置: 类 BlockBrokenMineral
/path/to/my/mc/project/build/sources/main/java/com/flemmli97/runecraftory/common/blocks/BlockBrokenMineral.java:47: 错误: 找不到符号
	public EnumMineralTier getTier()
	       ^
  符号:   类 EnumMineralTier
  位置: 类 BlockBrokenMineral
/path/to/my/mc/project/build/sources/main/java/com/flemmli97/runecraftory/common/blocks/BlockMineral.java:12: 错误: 找不到符号
import com.flemmli97.runecraftory.common.lib.enums.EnumMineralTier;
                                                  ^
  符号:   类 EnumMineralTier
  位置: 程序包 com.flemmli97.runecraftory.common.lib.enums
/path/to/my/mc/project/build/sources/main/java/com/flemmli97/runecraftory/common/blocks/BlockMineral.java:40: 错误: 找不到符号
    private final EnumMineralTier tier;
                  ^
  符号:   类 EnumMineralTier
  位置: 类 BlockMineral
/path/to/my/mc/project/build/sources/main/java/com/flemmli97/runecraftory/common/blocks/BlockMineral.java:41: 错误: 找不到符号
	public BlockMineral(EnumMineralTier tier) {
	                    ^
  符号:   类 EnumMineralTier
  位置: 类 BlockMineral
21 个错误
 FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':compileJava'.
> Compilation failed; see the compiler error output for details.

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.

BUILD FAILED

It seems class EnumMineralTier and LibPotions is missing.

**Comment by Flemmli97** [comment]
can you try again? there was lot of changes and i dont know what broke or what not but should be fixed now

**Comment by Baytars** [comment]
> can you try again? there was lot of changes and i dont know what broke or what not but should be fixed now

Apparently EnumMineralTier.java and LibPotions.java is missing and not included in your code.😂
