### ISSUE TITLE
missing textures

### ISSUE THREAD

**Issue by Warbringer12** [Flemmli97/RuneCraftory#3]
### Modloader

Forge

### Minecraft version

1.18.2

### Modloader version

40.1.0

### Mod version

1.0.2

### TenshiLib version

1.6.7

### Description

missing textures

### Steps to reproduce

1. loaded in
2. looked at jei
3. saw missing textures

### Mods that might affect the issue

jei

### Logs

not needed

**Comment by Flemmli97** [comment]
yes lots of items dont have textures still
