### ISSUE TITLE
so_many_enchants-1.7.0 (1.18) + runecraftory-1.18.2-1.3.1-forge = crash

### ISSUE THREAD

**Issue by luffykick** [Flemmli97/RuneCraftory#5]
### Modloader

Forge

### Minecraft version

1.18.2

### Modloader version

40.1.84

### Mod version

1.3.1

### TenshiLib version

1.6.11

### Description

Mod interaction crash with so_many_enchants-1.7.0 (1.18)

### Steps to reproduce

1. Load "so_many_enchants-1.7.0 (1.18)" with "runecraftory-1.18.2-1.3.1-forge"
2. Crash...
3. Cry to dev to fix the issue.

### Mods that might affect the issue

runecraftory-1.18.2-1.3.1-forge
so_many_enchants-1.7.0 (1.18)

### Logs

So Many Enchants!!! (so_many_enchants) encountered an error during the common_setup event phase
		java.lang.IllegalStateException: Point of interest types rf4_skill_poi and enchantment_table both list Block{minecraft:enchanting_table} in their blockstates, this is not allowed. Blockstates can only have one point of interest type each.

**Comment by Flemmli97** [comment]
forgot to close but fixed since 1.5.0
