### ISSUE TITLE
[Feature Request]: Put some images on the CurseForge page

### ISSUE THREAD

**Issue by YivanLiu** [Flemmli97/RuneCraftory#6]
### Suggestions

Putting some images on the CurseForge page can make the introduction more attractive. I am a Rune Factory fans and this mod is an marvelous job and you keep updating it, but the downloads does not match your effort. 

### Solution

Pictures advertise better than only words I think.

**Comment by Flemmli97** [comment]
wanted at least some decent art and content before doing that but done now
